name: publish
on:
  push:
    tags: ["v*"]     # publish when you push a tag like v1.0.0

permissions:
  contents: read
  id-token: write     # required for OIDC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@v1
        # no token needed; OIDC is used automatically
        # if you set an environment in the ruleset, add:
        # env:
        #   PIPY_ENVIRONMENT: pypi
