name: tests

on:
  push:
    branches: ["**"]
    paths:
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/workflows/tests.yml"
  pull_request:
    branches: ["**"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install project + test deps
        run: |
          python -m pip install --upgrade pip
          # If you have a dev extra, this will install pytest, etc.
          pip install -e ".[dev]" || (
            pip install -e . &&
            pip install pytest
          )

      - name: Run tests
        run: pytest -q
